global:
  scrape_interval:     5s

  external_labels:
      monitor: 'belisce-platform-api'

rule_files:

scrape_configs:
  - job_name: 'belisce'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:5000']