"""add_base_model

Revision ID: 371c1065f614
Revises: d2faa340bf03
Create Date: 2019-10-20 09:38:27.791113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '371c1065f614'
down_revision = 'd2faa340bf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column(
        'created_date', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column(
        'last_update', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column(
        'uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'roles', ['uuid'])
    op.add_column('users', sa.Column(
        'created_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column(
        'last_update', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column(
        'uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'uuid')
    op.drop_column('users', 'last_update')
    op.drop_column('users', 'created_date')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'uuid')
    op.drop_column('roles', 'last_update')
    op.drop_column('roles', 'created_date')
    # ### end Alembic commands ###
