"""Add category model

Revision ID: 63d074edd232
Revises: d8324060a3d6
Create Date: 2020-02-26 15:23:13.199131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d074edd232'
down_revision = 'd8324060a3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
