"""Add relationship between article and user

Revision ID: d8324060a3d6
Revises: ca3be7d20d4d
Create Date: 2020-02-26 15:11:08.537222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8324060a3d6'
down_revision = 'ca3be7d20d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
