"""Add notification flags to user model

Revision ID: fb9bd0ec85c1
Revises: 1f459209f6da
Create Date: 2020-03-01 09:12:09.792670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9bd0ec85c1'
down_revision = '1f459209f6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allow_mail_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('allow_push_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allow_push_notifications')
    op.drop_column('users', 'allow_mail_notifications')
    # ### end Alembic commands ###
